let shopItemsData = [
    {
      id: "jfhgbvnscs",
      name: "Casual Shirt",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-1.jpg",
    },
    {
      id: "ioytrhndcv",
      name: "Office Shirt",
      price: 100,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-2.jpg",
    },
    {
      id: "wuefbncxbsn",
      name: "T Shirt",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-3.jpg",
    },
    {
      id: "thyfhcbcv",
      name: "Mens Suit",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-4.jpg",
    },
    {
        id: "thyfhcbcv",
        name: "Office Wear",
        price: 500,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-6.jpg.jpg",
      },
      {
        id: "thyfhcbcv",
        name: "Womens Handbag",
        price: 2000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-7.jpg.jpg",
      },
      {
        id: "thyfhcbcv",
        name: "Womens Handbag",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-8.jpg.jpg",
      },
      {
        id: "thyfhcbcv",
        name: "Rolex Watch",
        price: 3000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-9.jpg.jpg",
      },
      {
        id: "thyfhcbcv",
        name: "Oraimo Watch",
        price: 1000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-10.jpg.jpg",
      },
      {
        id: "thyfhcbcv",
        name: "Classic Watch",
        price: 3000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-11.jpg.jpg",
      },
      {
        id: "thyfhcbcv",
        name: "Mens T'shirt",
        price: 5000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/product-8.jpg",
      },
      {
        id: "ddfgfgdgdgdd",
        name: "Sneakers",
        price: 3000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/Shoes.jpg",
      },
    
  ];